
ord_names = {
    1: b'OleUIAddVerbMenuA',
    2: b'OleUICanConvertOrActivateAs',
    3: b'OleUIInsertObjectA',
    4: b'OleUIPasteSpecialA',
    5: b'OleUIEditLinksA',
    6: b'OleUIChangeIconA',
    7: b'OleUIConvertA',
    8: b'OleUIBusyA',
    9: b'OleUIUpdateLinksA',
    10: b'OleUIPromptUserA',
    11: b'OleUIObjectPropertiesA',
    12: b'OleUIChangeSourceA',
    13: b'OleUIAddVerbMenuW',
    14: b'OleUIBusyW',
    15: b'OleUIChangeIconW',
    16: b'OleUIChangeSourceW',
    17: b'OleUIConvertW',
    18: b'OleUIEditLinksW',
    19: b'OleUIInsertObjectW',
    20: b'OleUIObjectPropertiesW',
    21: b'OleUIPasteSpecialW',
    22: b'OleUIPromptUserW',
    23: b'OleUIUpdateLinksW',
}