
ord_names = {
    500: b'NDdeShareAddA',
    501: b'NDdeShareDelA',
    502: b'NDdeShareEnumA',
    503: b'NDdeShareGetInfoA',
    504: b'NDdeShareSetInfoA',
    505: b'NDdeGetErrorStringA',
    506: b'NDdeIsValidShareNameA',
    507: b'NDdeIsValidAppTopicListA',
    508: b'NDdeSpecialCommandA',
    509: b'NDdeGetShareSecurityA',
    510: b'NDdeSetShareSecurityA',
    511: b'NDdeGetTrustedShareA',
    512: b'NDdeSetTrustedShareA',
    513: b'NDdeTrustedShareEnumA',
    600: b'NDdeShareAddW',
    601: b'NDdeShareDelW',
    602: b'NDdeShareEnumW',
    603: b'NDdeShareGetInfoW',
    604: b'NDdeShareSetInfoW',
    605: b'NDdeGetErrorStringW',
    606: b'NDdeIsValidShareNameW',
    607: b'NDdeIsValidAppTopicListW',
    608: b'NDdeSpecialCommandW',
    609: b'NDdeGetShareSecurityW',
    610: b'NDdeSetShareSecurityW',
    611: b'NDdeGetTrustedShareW',
    612: b'NDdeSetTrustedShareW',
    613: b'NDdeTrustedShareEnumW',
}